proxies:
  - name: "AWS-Hysteria"
    type: hysteria2
    server: toxqiu.ccwu.cc
    port: 443
    password: 8zPJSHleGlmXaDFsm2FPKPJP
    sni: toxqiu.ccwu.cc
    udp: true

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - AWS-Hysteria

rules:
  - MATCH,PROXY
